src/config/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
]

src/catalog/forms.py
from datetime import datetime

from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.models import inlineformset_factory
from django.utils.translation import ugettext as _

from cloudinary.forms import CloudinaryFileField
from dal import autocomplete

from catalog.entity_resource_data_handlers import EntityResourceTypeFactory
from catalog.models import Collection, CollectionItem, EntityResource


class EntityResourceForm(forms.ModelForm):

    url = forms.URLField(required=False)
    image = CloudinaryFileField(required=False)
    text = forms.CharField(required=False)

    class Meta:
        model = EntityResource
        exclude = ("data",)
        fields = "__all__"
        widgets = {"entity": autocomplete.ModelSelect2(url="entity_user_autocomplete")}

    def clean(self):
        """
        Clean the data
        :return:
        """
        cleaned_data = super(EntityResourceForm, self).clean()
        type = cleaned_data.get("type")

        if type not in [index[0] for index in EntityResource.RESOURCE_TYPES]:
            raise forms.ValidationError(
                _("{type} is an unknown EntityResource type".format(type=type))
            )
        handler = EntityResourceTypeFactory.get_handler_by_type(type)
        handler.validate(cleaned_data)


class CollectionForm(forms.ModelForm):

    start_date = forms.CharField(widget=AdminDateWidget(attrs={"class": "datepicker"}))
    end_date = forms.CharField(widget=AdminDateWidget(attrs={"class": "datepicker"}))
    name = forms.CharField()

    class Meta:
        model = Collection
        exclude = ("template", "shared_with", "name")
        fields = ()

    class Media:
        js = (
            "js/class.js",
            "js/catalog/collection_form_handlers.js",
        )

    def clean(self):
        """
        Create the name from the start date, the end date and the

        :return:
        """
        cleaned_data = super(CollectionForm, self).clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")
        verbose_name = cleaned_data.get("name")

        startobj = datetime.strptime(start_date, "%d %B, %Y")
        endobj = datetime.strptime(end_date, "%d %B, %Y")

        self.cleaned_data["name"] = "{0} ({1} - {2})".format(
            verbose_name, startobj.strftime("%d/%m"), endobj.strftime("%d/%m")
        )


class CollectionEntityForm(forms.ModelForm):
    """
    CollectionEntityForm
    """

    def __init__(self, *args, **kwargs):
        super(CollectionEntityForm, self).__init(*args, **kwargs)

    class Meta:
        model = CollectionItem
        fields = "__all__"


CollectionEntityFormset = inlineformset_factory(
    Collection, CollectionItem, form=CollectionEntityForm, can_delete=True, extra=3
)

src/templates/organisms/collections/create.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Create collection" %}{% endblock %}

{% block content %}
    <h1>{% trans "Create collection" %}</h1>
    <form action="" method="post" id="collection_form">{% csrf_token %}
        <div class="row">
            <div class="col s12">
                <label for="id_name">{{ form.name.label }}</label>
                {{ form.name}}
            </div>
            <div class="col s6">
                <label for="id_start_date">{{ form.start_date.label }}</label>
                {{ form.start_date }}
            </div>
            <div class="col s6">
                <label for="id_end_date">{{ form.end_date.label }}</label>
                {{ form.end_date }}
            </div>
            <input type="hidden" name="collection_relations" id="collection_relations" />
        </div>

        <div id="output_container"></div>
        <div id="relational_form" class="row hide">
            <div class="col s3">
                <input name="collection_itemform['date'][]" type="hidden" class="datefield"/>
                <div class="datefield_display"></div>
            </div>
            <div class="col s5 autocomplete ac-input">
                <input name="collection_itemform['entity'][]" data-beloworigin="true" class="entity" type="text" autocomplete="off" placeholder="Search for entity..." />
            </div>
            <div class="col s4">
                <textarea name="collection_itemform['note'][]" class="note" placeholder="Enter an optional note"></textarea>
            </div>
        </div>
        <input type="submit" value="Save" class="btn"/>
    </form>
{% endblock %}

{% block scripts_bottom %}
    <script type="text/javascript" src="{% static "js/class.js" %}"></script>
    <script type="text/javascript" src="{% static "js/lib/date_util.js" %}"></script>
    <script type="text/javascript" src="{% static "js/vendor/jquery.materialize-autocomplete.js" %}"></script>
    <script type="text/javascript" src="{% static "js/catalog/collection_form_handlers.js" %}"></script>
{% endblock %}}

src/templates/organisms/collections/detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    {% with template_name=object.template|stringformat:"s"|add:"/collectiondetail.html" %}
        {% include "molecules/collectiontypes/"|add:template_name  %}
    {% endwith %}
{% endblock %}

src/templates/organisms/collections/overview.html
{% load i18n %}
<h2>
    {% trans "All collections" %}
    {% with icon="add" title="Add a collection" extra_class=" grey right" %}
        {% url 'collection_create' as hyperlink %}
        {% include "atoms/buttons/icon_floating.html" %}
    {% endwith %}
</h2>
<div class="collection">
    {% for collection in collections %}
        {% with template_name=collection.template|stringformat:"s"|add:"/collectionoverview_listitem.html" %}
            {% include "molecules/collectiontypes/"|add:template_name  %}
        {% endwith %}
    {% empty %}
        {% trans "Collection list is empty" %}
    {% endfor %}
</div>