src/config/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
]

src/catalog/models.py
import json

from django.conf import settings
from django.db import models


class PrivateShareableModel(models.Model):
    """
    A model that's got an owner, and can be shared with a list of owners.

    """

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=True)

    class Meta:
        abstract = True


class TimestampedModel(models.Model):
    """
    A model having a creation date and maintains the latest update

    """

    created_at = models.DateTimeField(
        verbose_name="Creation date", auto_created=True, auto_now_add=True
    )
    updated_at = models.DateTimeField(verbose_name="Last update", auto_now_add=True)

    class Meta:
        abstract = True


class Tag(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Collection(PrivateShareableModel, TimestampedModel):
    """
    A list of items
    """

    TYPE_LIST = (("default", "Default Template"),)
    name = models.CharField(max_length=255)
    template = models.CharField(max_length=50, choices=TYPE_LIST)
    shared_with = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL, related_name="co_owners", blank=True
    )

    def template_path(self):
        return "organisms"

    def __str__(self):
        return self.name


class Entity(PrivateShareableModel, TimestampedModel):
    """
    An entity that can be added into a list. It has a name, an image, an owner, it can be public as well.
    """

    name = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag, related_name="tags")
    rating = models.IntegerField(blank=True, default=None)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Entities"


class EntityResource(models.Model):

    RESOURCE_TYPES = (("image", "Image"), ("url", "Link"), ("text", "Text"))

    entity = models.ForeignKey(
        to=Entity, on_delete=models.CASCADE, blank=True, default=None
    )

    type = models.CharField(max_length=25, choices=RESOURCE_TYPES, default="url")
    data = models.TextField()
    description = models.CharField(max_length=255)

    def __str__(self):
        return "{0} - ({1})".format(self.entity, self.type)

    @property
    def data_dict(self):
        return json.loads(self.data)


class Note(models.Model):
    """
    A simple model to add multiple notes to an item in a list.

    """

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    value = models.TextField()

    def __str__(self):
        if len(self.value) > 5:
            return "{}...".format(self.value[:4])
        return self.value


class CollectionItem(models.Model):
    """
    Relational model for managing items on a list.

    list
    entity
    entry_description
    note ~

    """

    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    item = models.ForeignKey(Entity, on_delete=models.CASCADE, blank=True, null=True)
    entry_description = models.CharField(max_length=100)
    notes = models.ForeignKey(Note, on_delete=models.CASCADE, blank=True, null=True)

src/templates/molecules/collectiontypes/default/collectiondetail.html
<div class="collection with-header">
    <div class="collection-header">
        <h5>
            {% with icon="chevron_left" title="back"%}
                {% url 'dashboard' as hyperlink %}
                {% include "atoms/buttons/icon_floating.html" %}
            {% endwith %}
            {{ object.name }}
        </h5>
    </div>
    {% for key, entity in entity_list.items %}
        <div class="collection-item weekview valign-wrapper hoverable row">
            <div class="col s1 datefield">
                {{ key }}
            </div>
            {% if entity %}
                <div class="col s9">
                    <div class="left item-content">
                        {% if entity.item %}
                            {{ entity.item }}
                        {% endif %}
                    {% if entity.notes %}
                        <div class="right meta-content">
                            {{ entity.notes.value }}
                        </div>
                    {% endif %}
                    </div>
                </div>
                <div class="col s2 references">
                    {% for resource in entity.item.entityresource_set.all %}
                        {% with template_name="short_"|add:resource.type|stringformat:"s"|add:".html" %}
                            {% include "molecules/resources/"|add:template_name  %}
                        {% endwith %}
                    {% endfor %}
                </div>
            {% else %}
                <div class="col s11">
                    <div class="left item-content">
                        -
                    </div>
                </div>
            {% endif %}

        </div>
    {% endfor %}
</div>

src/templates/molecules/collectiontypes/default/collectionoverview_listitem.html
<div class="collection-item">
    <div class="title">
        <a href="{% url "collection_detail" pk=collection.id %}">{{ collection.name }}</a>
        <span class="badge meta-title">type {{ collection.template }} - {{ collection.owner }}</span >
    </div>
</div>